### ISSUE TITLE
Add real state change notification

### ISSUE THREAD

**Issue by fpompermaier** [BOSSoNe0013/NeoJava#2]
At the moment the state change notification works only when the state change is fired from NeoJava, so for example I change the state of a pin using 

```
sudo echo 0 > /sys/class/gpio/gpio18/value
```

my application is not notified. What do you think about adding a real listener on file changes (for example using the Watch Service API for example, e.g. http://www.codejava.net/java-se/file-io/file-change-notification-example-with-watch-service-api)?

**Comment by fpompermaier** [comment]
if you compare your branch with mine (https://github.com/BOSSoNe0013/NeoJava/compare/master...fpompermaier:master) you can see a simple experimental version of such a listener..there are lot of things to improve but could be a good start..what do you think?

**Comment by BOSSoNe0013** [comment]
Hi Flavio,
I'm not at home for the week-end i i'll have a look on tuesday. Have a nice day.
